### ISSUE TITLE
Drawing pad

### ISSUE THREAD

**Issue by Gerzer** [Gerzer/Euclidean-algorithm#1]
Is it worth the effort to add an HTML drawing pad for calculations using the `<canvas>` tag? We could potentially embed someone else's in an `<iframe>` if it has the right licenses...

**Comment by Exavis** [comment]
That would be cool, and helpful I think.
Let's try to find an <iframe> with right licenses that could work.

**Comment by Gerzer** [comment]
Alright, will start looking. Could use some help with the search... :)

**Comment by Gerzer** [comment]
Just asked the owners of https://github.com/eaw20024/Drawing-Pad permission to embed their project in ours. Well, I guess we'll see how things go!

**Comment by Exavis** [comment]
Alright! Sorry I haven't been responding quickly.
If you don't mind, I'll like to make some changes on the design and layout
of the project.. of course we can look at both versions.

**Comment by Gerzer** [comment]
That sounds great! I just want to email you privately to work out the details.

**Comment by Gerzer** [comment]
I can't seem to find your email address. Could you email me instead of me emailing you? Thanks!

**Comment by Exavis** [comment]
Through github? Or regular email?

**Comment by Gerzer** [comment]
Regular email

**Comment by Exavis** [comment]
New email chain okay?

**Comment by Gerzer** [comment]
If you mean you want to create a new, private chain, then yes, go ahead. :)

**Comment by Exavis** [comment]
I have been working on the project but will need to work on it more so yeah.

**Comment by Gerzer** [comment]
Sounds good
